# -*- coding: utf-8 -*-
"""Copy of Sample EDA Submission Template.ipynb(Hotel Booking Analysis)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1juU4QU0bTyDxzbFAjvv00ZkkyEEK9eLX

# **Project Name**    -  Hotel Booking Analysis

##### **Project Type**    - EDA
##### **Contribution**    - Individual

# **Project Summary -**

This project is related to Hotel Booking having two type of hotel description that is City Hotel and resort Hotel. In this data set total number of rows 119390 and 32 columns. On the work flow we have to devide into three part that is Data Collection, Data Cleaning and manipulation, and Exploratory Data Analysis.\
First step of the data collection find the different columns which is done by coding head(), tail(), info(), describe(), columns and some other method use for the data collections. As we further moved we find the unique value of each columns and also check the data type of each columns, find the some columns not in accurate data types which correctedit later done in data cleaning part and as well as duplicate data items must be removed as we find the duplicate items equall to 86425 which is droped from dataset later.\
Before visualize any data from the data set we have to do data wrangling, for that we checked the null value of all columns. After checking, we are getting a columns which have more number of null values, drop that columns by using the drop method. We have to find the null value in some columns, filling these value with necessary value as per requirement by using fillna().\
\
Different visulazition chart used to better understanding of the business objective.

# **GitHub Link -**

Provide your GitHub Link here.

# **Problem Statement**

Have you ever wondered when the best time of year to book a hotel room is? 

Or 

the optimal length of stay in order to get the best daily rate? 

What if you wanted to predict whether or not a hotel was likely to receive a disproportionately high number of special requests? 

This hotel booking dataset can help you explore those questions!\
\
This data set contains booking information for a city hotel and a resort hotel, and includes information such as when the booking was made, length of stay, the number of adults, children, and/or babies, and the number of available parking spaces, among other things. All personally identifying information has been removed from the data.Explore and analyze the data to discover important factors that govern the bookings.

#### **Define Your Business Objective?**

Analyze the data on booking of  the City Hotel and Resort Hotel to gain deep understanding on the different factor that will be affect the booking.

# **General Guidelines** : -

1.   Well-structured, formatted, and commented code is required. 
2.   Exception Handling, Production Grade Code & Deployment Ready Code will be a plus. Those students will be awarded some additional credits. 
     
     The additional credits will have advantages over other students during Star Student selection.
       
             [ Note: - Deployment Ready Code is defined as, the whole .ipynb notebook should be executable in one go
                       without a single error logged. ]

3.   Each and every logic should have proper comments.
4. You may add as many number of charts you want. Make Sure for each and every chart the following format should be answered.
        

```
# Chart visualization code
```
            

*   Why did you pick the specific chart?
*   What is/are the insight(s) found from the chart?
* Will the gained insights help creating a positive business impact? 
Are there any insights that lead to negative growth? Justify with specific reason.

5. You have to create at least 20 logical & meaningful charts having important insights.


[ Hints : - Do the Vizualization in  a structured way while following "UBM" Rule. 

U - Univariate Analysis,

B - Bivariate Analysis (Numerical - Categorical, Numerical - Numerical, Categorical - Categorical)

M - Multivariate Analysis
 ]

# ***Let's Begin !***

## ***1. Know Your Data***

### Import Libraries
"""

# Import Libraries
import numpy as np
import pandas as pd
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns

"""### Dataset Loading"""

# Load Dataset
from google.colab import drive
drive.mount('/content/drive')

# File Path
file_path = '/content/drive/MyDrive/AlmaBetter Project1/Hotel Bookings.csv'

# DataFrame for the Hotel Booking
hotel_df = pd.read_csv(file_path)

"""### Dataset First View"""

# Dataset First Look
hotel_df

"""### Dataset Rows & Columns count"""

# Dataset Rows & Columns count
Number_of_Rows = hotel_df[hotel_df.columns[0]].count()     # Also Use {"hotel_df.shape[0]","len(hotel_df)","len(hotel_df.index)"}
Number_of_columns = len(hotel_df.columns)                  # Also Use {"hotel_df.shape[1],len(hotel_df.count())"}
print(f'Number of Rows in Hotel Booking Dataframe = {Number_of_Rows}, \n Number of Columns in Hotel Booking Dataframe = {Number_of_columns}')

"""### Dataset Information"""

# Dataset Info
hotel_df.info()

"""#### Duplicate Values"""

# Dataset Duplicate Value Count
len(hotel_df[hotel_df.duplicated()])                              # Also use {"len(hotel_df[hotel_df.duplicated() == True])"}

"""#### Missing Values/Null Values"""

# Missing Values/Null Values Count
hotel_df.isna().sum().sum()

# Visualizing the missing values
hotel_df.isna().sum()

# Analysis of unique year for Hotel Booking Dataframe
hotel_df.arrival_date_year.unique()

"""### What did you know about your dataset?

*   Hotel Booking Dataset contain the booking information from 2015 to 2017  for a city hotel and a resort hotel.
*   Number of rows in Hotel Booking Dataset = 119390
*   Number of columns in Hotel Booking Dataset = 32
*   Number of Duplicate value in the Dataset = 31994
*   Total number of missing value in the dataset is 129425, which having contain the following columns:
    1. missing value in children columns = 4
    2. missing value in country columns = 488
    3. missing value in agent columns = 16340
    4. missing value in company columns = 112593

## ***2. Understanding Your Variables***
"""

# Dataset Columns
hotel_df.columns

# Dataset Describe
hotel_df.describe(include = 'all')

"""### Variables Description

* **Hotel               :** H1 = Resort Hotel & H2 = City Hotel

* **is_canceled          :** If the booking was canceled(1) or not(0)

* **lead_time               :**Number of days that elapsed between the entering date of the booking into the PMS and the arrival date

* **arrival_date_year            :**Year of arrival date

* **arrival_date_month           :**Month of arrival date

* **arrival_date_week_number        :**Week number for arrival date

* **arrival_date_day_of_month             :**Day of arrival date

* **stays_in_weekend_nights         :**Number of weekend nights(Saturday and Sunday) the guest stayed or booked to stay at the hotel

* **stays_in_week_nights         :**Number of week nights(Monday to Friday) the guest stayed or booked to stay at the hotel

* **adults          :**Number of adults

* **children          :**Number of children

* **babies         :**Number of babies

* **meal         :**Kind of meal opted for

* **country        :**Country code

* **market_segment      :**Which segment the customer belongs to

* **distribution_channel         :**How the customer accessed the stay-corporate booking/Direct/TA.To

* **is_repeated_guest         :**Guest coming for first time or not

* **previous_cancellation        :**Was there a cancellation before

* **previous_booking_not_canceled    :**Count of previous bookings

* **reserved_room_type            :**Type of room reversed

* **assigned_room_type            :**Type of room assigned

* **booking_changes            :**Count of changes made to booking

* **deposite_type            :**Deposite type

* **agent            :**Booked through agent

* **company            :**Company

* **days_in_waiting_list            :**Number of days in waiting list

* **customer_type            :**Type of customer

* **adr            :** Average Daily Rate

* **required_car_parking_space            :**If car parking is required

* **total_of_special_requests           :**Number of additional special requirements

* **reservation_status            :**Reservation of status

* **reservation_status_date            :**Date of the specific status

### Check Unique Values for each variable.
"""

# Check Unique Values for each variable.
for i in hotel_df.columns.tolist():
  print("Number of unique values in ",i,"is",hotel_df[i].nunique(),".")

"""## 3. ***Data Wrangling***

### Data Wrangling Code
"""

# Write your code to make your dataset analysis ready.
#  viewing columns and thinking what to keep
hotel_df.columns

# final column in Dataframe
columns_to_keep= ['hotel', 'is_canceled', 'lead_time', 'arrival_date_year',
       'arrival_date_month', 'arrival_date_week_number',
       'arrival_date_day_of_month', 'stays_in_weekend_nights',
       'stays_in_week_nights', 'adults', 'children','babies','meal',
       'country', 'market_segment', 'distribution_channel',
       'is_repeated_guest', 'previous_cancellations',
       'previous_bookings_not_canceled', 'reserved_room_type',
       'assigned_room_type', 'deposit_type','agent', 'customer_type', 'adr',
       'required_car_parking_spaces', 'total_of_special_requests']

# Create a copy of the current hotel_df and assigning to df without disturbing the original dataset
df = hotel_df[columns_to_keep].copy()

# First view of new_hotel_df
df

#viewing the info in the new_hotel_df
df.info()

# find out how many columns have null values 
df.isna().sum()

# fill the NULL value of children column in df by 0
df['children'].fillna(0,inplace=True)

# convert the datatype of the children column into int
df['children'] = df['children'].astype(int)

# fill the NULL value with N/A of the country,agent in df
df['country'].fillna('N/A',inplace=True)
df['agent'].fillna('N/A',inplace=True)

#just doing a double check and making sure that we are ready to proceed
df.info()

# Check the Duplicate row in the hotel booking dataframe
len(df[df.duplicated() == True])

# Drop the duplicate value in the hotel booking dataframe(hotel_df) assign to new_hotel_df
new_hotel_df = df.drop_duplicates()

#info of new_hotel_df
new_hotel_df.info()

# shape of the new_hotel_df
new_hotel_df.shape

#No. of bookings is_canceled on City Hotel and Resort Hotel
new_hotel_df.groupby(['hotel','is_canceled'])['is_canceled'].count()

#No. of Yearly bookings on City Hotel and Resort Hotel
new_hotel_df.groupby(['hotel','arrival_date_year'])['arrival_date_year'].count()

#No. of monthly bookings on City Hotel and Resort Hotel
new_hotel_df.groupby(['hotel','arrival_date_month'])['arrival_date_month'].count()

# Sum of adults Booking 
new_hotel_df['adults'].sum()

# Sum of children Booking
new_hotel_df['children'].sum()

# Sum of babies Booking
new_hotel_df['babies'].sum()

# count the Type of meals
new_hotel_df['meal'].value_counts()

#No. of bookings on market segment on City Hotel and Resort Hotel
new_hotel_df.groupby(['hotel','market_segment'])['market_segment'].count()

#No. of bookings on type of distribution_channel
new_hotel_df.groupby(['hotel','distribution_channel'])['distribution_channel'].count()

#No. of bookings guest is repeating or not on City Hotel and Resort Hotel :
new_hotel_df.groupby(['hotel','is_repeated_guest'])['is_repeated_guest'].count()

# sum of total special request:
new_hotel_df['total_of_special_requests'].sum()

# Adding total staying days in hotels
new_hotel_df['total_stay'] = new_hotel_df['stays_in_weekend_nights']+ new_hotel_df['stays_in_week_nights']

# Adding total people num as column, i.e. total people num = num of adults + children + babies
new_hotel_df['total_people'] = new_hotel_df['adults']+new_hotel_df['children']+new_hotel_df['babies']

# Adding revinue by using total_stay * adr
new_hotel_df['revenue'] = new_hotel_df['total_stay'] * new_hotel_df['adr']

# Calculate total revenune
new_hotel_df['revenue'].sum()

# Total revenue generating by City Hotel
city_hotel = new_hotel_df[new_hotel_df['hotel'] == 'City Hotel']
city_hotel['revenue'].sum()

# Total revenue generating by Resort Hotel
resort_hotel = new_hotel_df[new_hotel_df['hotel'] == 'Resort Hotel']
resort_hotel['revenue'].sum()

"""### What all manipulations have you done and insights you found?

### **We hhave to done few manipulation in the data.**
\
**Addition of columns:   **\
**1. total_stay:** This columns we help us to evaluate the total number of customer stay in a week. We get this value by adding total number of stays_in_weekend_nights & stays_in_week_nights.\
**2. total_people:**  This columns help us to determine the total number of guest in the hotel. We get the value by adding of total number of adults, children and babies.\

**3. revenue:**  This columns help us to determine the profit and growth of the business. We get the value by multiplying adr and total_people.\
\
**Ignore the columns:** 


*   We have to ignore the columns which have convay to less informmnation or more numbers of null values are present. In the following analysis we have to ignore the company,reservation_status, reservation_status_date,booking_change
\

**Remove is_null value:** Before the visulize any data from the data set we have to do data wrangling, for that we have to check the null value for all the columns and if we find the null value then filling these null value with necessary value as per requirement by using .fillna() method.\

**Removed the duplicate entity:**  We have to check the duplicacy in the data and we found there are few rows have duplicate data, So we have removed those rows from data set by using .drop_duplicates() method.

## ***4. Data Vizualization, Storytelling & Experimenting with charts : Understand the relationships between variables***

#### Chart - 1- Pie Chart on Dependant Variable i.e., Hotel
"""

# Chart - 1 visualization code
# Dependant Column Value Counts
print(new_hotel_df.hotel.value_counts())
print("\n")
# Dependant Variable Column Visualization
new_hotel_df['hotel'].value_counts().plot(kind='pie',
                              figsize=(15,8),
                               autopct="%1.2f%%",
                               startangle=90,
                               shadow=False,
                               labels=['City Hotel(%)','Resort Hotel(%)'],
                               colors=['blue','green'],
                               explode=[0,1]
                              )

"""##### 1. Why did you pick the specific chart?

To repesent the data of the both hotels in pecentage and find the hotel having more booking.

##### 2. What is/are the insight(s) found from the chart?

Here we found that the booking number is higher in city hotel which is 61.13% and resort hotel which is 38.87%. Hence we can say that city hotel having more customer.

##### 3. Will the gained insights help creating a positive business impact? 
Are there any insights that lead to negative growth? Justify with specific reason.

Yes, here data of the both hotel provide some positive business impact:-
1. City Hotel: It's provide more services to atteract more customer to generate more revenue.
2. Resort Hotel: To check the services and also find the how to increse customer as compare to city hotel.

#### Chart - 2-percentage of bookings yearly
"""

# Chart - 2 visualization code
print(new_hotel_df.arrival_date_year.value_counts())
print("\n")
# Dependant Variable Column Visualization
new_hotel_df['arrival_date_year'].value_counts().plot(kind='pie',
                              figsize=(15,8),
                               autopct="%1.2f%%",
                               startangle=90,
                               shadow=False,
                               labels=['2016(%)','2017(%)','2015(%)'],
                               colors=['skyblue','green','red'],
                               explode=[1,1,1]
                              )

"""##### 1. Why did you pick the specific chart?

To repesent the hotel booking data in percentage having which year busines is more.

##### 2. What is/are the insight(s) found from the chart?

Here we found that the booking number is higher in 2016 which is 48.50%, in 2017 is 36.26% and lower in 2015 which is 15.23%. Hence we can say that  hotel having more business in 2016.

##### 3. Will the gained insights help creating a positive business impact? 
Are there any insights that lead to negative growth? Justify with specific reason.

Yes, here data of the hotel booking having more in 2016, which is 48.50%. Now we check the services and check whether how to increase the customer in next segment.

#### Chart - 3- Count the number of booking in year wise of both type of hotels
"""

# Chart - 3 visualization code
sns.countplot (x= 'arrival_date_year', data=new_hotel_df , hue= 'hotel').set_title ('yearly_bookings')

"""##### 1. Why did you pick the specific chart?

In this section we have to done, represent the data of different year of differnt type of hotel booking analysis.

##### 2. What is/are the insight(s) found from the chart?

In this plot we have to found that business of the hotel booking is maximum in 2016 in each hotel. In 2015 both type of hotel having close to each other in business, but after city hotel perform better than resort hotel.

##### 3. Will the gained insights help creating a positive business impact? 
Are there any insights that lead to negative growth? Justify with specific reason.

Yes, here data of the both hotel provide some positive business impact:


1.   In year 2015 having approxmetaly same number of customer in both city and resort hotel, But after 2015 City hotel perform well as compared to resort hotel.
2.  After 2015 city hotel provide more services which is atteract to customer and done more business.

#### Chart - 4 - Monthly Booking
"""

# Chart - 4 visualization code
counts = new_hotel_df['arrival_date_month'].value_counts()
sns.barplot(counts.index, counts)
plt.xticks(rotation=45)
plt.tight_layout()

"""##### 1. Why did you pick the specific chart?

Here the graph show the frequency count the customer value in months wise, which gives the information which month is busy?

##### 2. What is/are the insight(s) found from the chart?

Here we find the maximum booking in August month and minimum booking in january month. Here top three booking month is august, jule, and may which means summer season is the peak of the guest comes inside hotel, and least top tree month are january, december, and november that means winter season have less business as compare to summer.

##### 3. Will the gained insights help creating a positive business impact? 
Are there any insights that lead to negative growth? Justify with specific reason.

Yes, here data of the hotel booking  provide some positive business impact. It's gives the maximum business in summer season and minimum in winter season, So we can povide well and atteractive services in summer season which improve our business.

#### Chart - 5 - Number of booking made by individuals from different countries
"""

# Chart - 5 visualization code
x = new_hotel_df.country.value_counts().head(10).plot (kind= 'bar');
for p in x.patches:
    x.annotate(str(p.get_height()), (p.get_x() , p.get_height()))

"""##### 1. Why did you pick the specific chart?

To show the top 10 data of the hotel booking on different type of country.

##### 2. What is/are the insight(s) found from the chart?

In this plot we have to found that business of the hotel booking is maximum in PRT country which is 27051.Most of the customers come from Portugal(PRT), Great Britain(GBR), France(FRA) and Spain(ESP).

##### 3. Will the gained insights help creating a positive business impact? 
Are there any insights that lead to negative growth? Justify with specific reason.

Yes, here data of the hotel booking in each country provide some positive business impact:-
1. Hotel booking is maximum in PRT which having 27051.
2. We have to provide the same setup of the services in other country which gives the atteraction and finally increase our business.

#### Chart - 6 - Varriation of adr and length of stay(total_stay)
"""

# Chart - 6 visualization code
plt.figure(figsize = (12,6))
sns.scatterplot(y = 'adr', x = 'total_stay', data = new_hotel_df)
plt.show()

"""##### 1. Why did you pick the specific chart?

Scatter plot gives the more information correlation of two or more measurement as the same time, Here we have to find the  the varriaton of the adr across the total_stay of the hotel booking.

##### 2. What is/are the insight(s) found from the chart?

On the above chart it is clear that adr decreases when the length of the total_stay of the hotel booking data increases.

##### 3. Will the gained insights help creating a positive business impact? 
Are there any insights that lead to negative growth? Justify with specific reason.

Yes, here data of the hotel booking provide some positive business impact. On the above chart it is clear that adr decreases when the length of the total_stay of the hotel booking data increases. This means for longer stay, the better deal for customer can be finalised.

#### Chart - 7 - Relationship between lead time and cancellations
"""

# Chart - 7 visualization code
a = new_hotel_df.groupby("lead_time")['is_canceled'].describe()
sns.scatterplot(x=a.index, y=a["mean"] * 100)

"""##### 1. Why did you pick the specific chart?

In the above plot we have to built the relationship between lead_time and cancellation of the hotel booking data.

##### 2. What is/are the insight(s) found from the chart?

In the above chart we can say that cancellation is directly affected by the lead time of the hotel booking data, that means as the length of the lead_time increases cancellation of the hotel booking increases.

##### 3. Will the gained insights help creating a positive business impact? 
Are there any insights that lead to negative growth? Justify with specific reason.

Yes, here data of the hotel booking provide some business impact. This chart povide the information the length of the lead_time and cancellation of the hotel booking, which helps to understanding the business.

#### Chart - 8 - Studying pattern of cancellations
"""

#finding out the mean
new_hotel_df.is_canceled.mean()

#mean individually for city/resort hotels
new_hotel_df.groupby("hotel")['is_canceled'].mean()

#no of cancellations WRT no of times booking has been cancelled
new_hotel_df.previous_cancellations.value_counts()

new_hotel_df.groupby('previous_cancellations').count()

# Chart - 8 visualization code
#how frequent are the previous cancelers in this cancelling game
sns.barplot(x= "previous_cancellations" ,y = "is_canceled", data = new_hotel_df)

"""##### 1. Why did you pick the specific chart?

This chart provide the cancsllation patern of the hotel booking.

##### 2. What is/are the insight(s) found from the chart?

In the following chart it's provide the information of the cancellation of the hotel booking. The mean value of the hotel booking is_canceled is 0.2737, and mean value of City hotel booking is_canceled is 0.2991 and mean value of Resort hotel booking is 0.2337. Hence we can say that booking of the city hotel is more canceled as compare to Resort hotel.

##### 3. Will the gained insights help creating a positive business impact? 
Are there any insights that lead to negative growth? Justify with specific reason.

Yes, here data of the hotel booking provide some positive business impact. It's provide the cancellation patern of the hotel booking which make sure to decrease the booking will cancelled.

#### Chart - 9 - Calculate cancel percentage of City Hotel and Resort Hotel
"""

# Selecting and counting number of cancelled bookings for each hotel.
cancelled_data = new_hotel_df[new_hotel_df['is_canceled'] == 1]
cancel_grp = cancelled_data.groupby('hotel')
df1 = pd.DataFrame(cancel_grp.size()).rename(columns = {0:'total_cancelled_bookings'})

# Counting total number of bookings for each type of hotel
grouped_by_hotel = new_hotel_df.groupby('hotel')
total_booking = grouped_by_hotel.size()
df2 = pd.DataFrame(total_booking).rename(columns = {0: 'total_bookings'})
df3 = pd.concat([df1,df2], axis = 1)

# Calculating cancel percentage 
df3['cancel_%'] = round((df3['total_cancelled_bookings']/df3['total_bookings'])*100,2)
print(df3)
# bar graph ploting
plt.figure(figsize = (10,5))
sns.barplot(x = df3.index, y = df3['cancel_%'])
plt.show()

"""##### 1. Why did you pick the specific chart?

Using this chart we have to show the percentage of cancellation of the each hotel type.

##### 2. What is/are the insight(s) found from the chart?

We have to found the 29.91% is canceled in City Hotel and 23.37% is canceled in resort hotel. In City hotel slightly more percent of cancelation than Resort hotel

##### 3. Will the gained insights help creating a positive business impact? 
Are there any insights that lead to negative growth? Justify with specific reason.

Yes, here data of the hotel booking provide some negative business impact.Here, we have to found the 29.91% is canceled in City Hotel and 23.37% is canceled in resort hotel.So, we can say that City hotel has higher cancellation rate, Which has to negative impact on the business.

#### Chart - 10 - Relationship between market segment and cancellation
"""

# Chart - 10 visualization code
sns.countplot(x='market_segment',data=new_hotel_df ,hue='is_canceled')
plt.title("Relationship between booking cancellations & market segment")
plt.xticks(rotation = 45)

"""##### 1. Why did you pick the specific chart?

Using this ploting let us try to understand what causes the people to cancel the booking.

##### 2. What is/are the insight(s) found from the chart?

In the chart we have to found that TA/TO has highest booking cancellation. Therefore, a booking via TA/TO is likely to get cancelled.

##### 3. Will the gained insights help creating a positive business impact? 
Are there any insights that lead to negative growth? Justify with specific reason.

Yes, here the chart gives the information to understand the busines impcat. The booking of TA/TO has highest booking cancellation.Let us see what causes the cancelation of bookings of rooms by customers \
 \
 One question can arise that may be longer waiting period or longer lead time causes the cancellation of bookings, let us check that.

#### Chart - 11 - Check the channel is mostly used for early booking of hotels
"""

# Chart - 11 visualization code
group_by_distribution_channel = new_hotel_df.groupby('distribution_channel')
df4 = pd.DataFrame(round(group_by_distribution_channel['lead_time'].median(),2)).reset_index().rename(columns = {'lead_time': 'median_of_lead_time'})
plt.figure(figsize = (10,5))
sns.barplot(x = df4['distribution_channel'], y = df4['median_of_lead_time'])
plt.show()

"""##### 1. Why did you pick the specific chart?

Using this plot we have to check the channel is mostly used for early booking of hotels.

##### 2. What is/are the insight(s) found from the chart?

TA/TO distribution channel have  mostly used for planning Hotel visits ahead of time. But for sudden visits other mediums has most preferred.

##### 3. Will the gained insights help creating a positive business impact? 
Are there any insights that lead to negative growth? Justify with specific reason.

Yes, here data of the hotel booking provide some positive business impact.It plot show that the relation between lead time and distribution channel which gives the TA/TO distribution channel have  mostly used for planning Hotel visits ahead of time, But for sudden visits other mediums has most preferred.

#### Chart - 12 - Plotting variation in adr with room type
"""

new_hotel_df['adr_pp']= new_hotel_df.adr/new_hotel_df.total_stay

# Chart - 12 visualization code
sns.barplot(data = new_hotel_df, x = 'reserved_room_type', y = 'adr_pp', hue = 'hotel')

"""##### 1. Why did you pick the specific chart?

Using this plot we have to find the variaton of adr(Average Daily rate) with room type.

##### 2. What is/are the insight(s) found from the chart?

In the following plot show the variation of adr(Average Daily Rate) with room tpye of each hotel, and maximum variation show on Resort hotel on  L type of Reserver Room Type.

##### 3. Will the gained insights help creating a positive business impact? 
Are there any insights that lead to negative growth? Justify with specific reason.

Yes, this graph ploting gives the variation of each hotel type of each reserved room type with adr, which gives the varion is slighly more in reserved room tpy of Resort Hotel as compare to City Hotel, Which affect the business.

#### Chart - 13 - Plotting variation in adr(Average Daily Rate) with room type of each market segment of the Hotel Booking
"""

# plotting variation in adr with room type of each market segment of the Hotel booking
sns.barplot(x= 'market_segment', y= 'adr_pp', hue= 'reserved_room_type', data= new_hotel_df)
plt.xticks(rotation = 45)

"""##### 1. Why did you pick the specific chart?

Using this plotting we have to find the variation in adr with room type of each market segment of the Hotel booking business.

##### 2. What is/are the insight(s) found from the chart?

Here, using plotting this chart we have to find the  variation in adr with room type of each market segment of the Hotel booking business, Which having maximum adr generated by Direct market segment of the hotel booking and minimum adr generating in Complementary market segment.

##### 3. Will the gained insights help creating a positive business impact? 
Are there any insights that lead to negative growth? Justify with specific reason.

Yes, It's gives the information of positive bisuness impact of the hotel booking analysis. In the graph we can say that the maximum business done by direct market segment and minimum in complementry market segment. So, we have to find the error of the complementry segment and it's improve it then which improve the hotel booking business.

#### Chart - 14 - Correlation Heatmap
"""

# Correlation Heatmap visualization code
df = new_hotel_df[['lead_time','previous_cancellations','previous_bookings_not_canceled','adr','required_car_parking_spaces','total_of_special_requests','total_stay','total_people']]
f, ax = plt.subplots(figsize=(10, 5))
sns.heatmap(df.corr(),annot = True,fmt='0.1f',annot_kws={'size':10},vmax =10,square=True)

"""##### 1. Why did you pick the specific chart?

A correlation matrix is a table showing correlation coefficients between variables. Each cell in the table shows the correlation between two variables. A correlation matrix is used to summarize data, as an input into a more advanced analysis, and as a diagnostic for advanced analyses. The range of correlation is [-1,1].

Thus to know the correlation between all the variables along with the correlation coeficients, i used correlation heatmap.

##### 2. What is/are the insight(s) found from the chart?

From the above correlation heatmap, we can see lead_time,previous_cancellations,previous_bookings_not_canceled,adr,required_car_parking_spaces,total_of_special_requests,total_stay,total_people positiveliy highly correlated with a value of 1.

1) Total stay length and lead time have slight correlation. This may means that for longer hotel stays people generally plan little before the the actual arrival.

2) adr is slightly correlated with total_people, which makes sense as more no. of people means more revenue, therefore more adr.

#### Chart - 15 - Pair Plot
"""

# Pair Plot visualization code
sns.pairplot(new_hotel_df,hue = 'hotel')

"""##### 1. Why did you pick the specific chart?

Pair plot is used to understand the best set of features to explain a relationship between two variables or to form the most separated clusters. It also helps to form some simple classification models by drawing some simple lines or make linear separation in our data-set.

Thus, I used pair plot to analyse the patterns of data and realationship between the features. It's exactly same as the correlation map but here you will get the graphical representation.

##### 2. What is/are the insight(s) found from the chart?

From the above chart I got to know, there are less linear relationship between variables and data poiunts aren't linearly separable.  In this whole pair plot, the importance of area code can be seen and the number of hotel with respect to different features are really insightful.

## **5. Solution to Business Objective**

#### What do you suggest the client to achieve Business Objective ? 
Explain Briefly.

Answer Here.

# **Conclusion**

*   year 2016 has most no of bookings.
*   city hotels are comparitively cheaper and more preferred as compared to resort hotels.
*  summers are most preferred by the people to make a booking.
*  Portugal sends most number of visitors in different hotels.
*  weekkdays and weekends don't have much to do with bookings.
*  people who have made a cancellation previously are much likely to cancel their bookings.
*  lead time is directly proportional to no of cancellations.
*  online bookings and the bookings with refundable deposit type has the most chances of cancellation.
*  In spring and autumn seasons dont have much to do with the varying prices.

### ***Hurrah! You have successfully completed your EDA Capstone Project !!!***
"""